-- Dandelion Effect schema for Supabase (PostgreSQL)

create table if not exists tenants (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists admin_users (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  username text not null,
  password_hash text not null,
  display_name text not null,
  twofa_enabled integer not null default 0,
  twofa_secret text,
  failed_login_count integer not null default 0,
  locked_until timestamptz,
  password_updated_at timestamptz,
  must_change_password integer not null default 0,
  created_at timestamptz not null default now(),
  unique (tenant_id, username)
);

create table if not exists tenant_settings (
  tenant_id bigint primary key references tenants(id) on delete cascade,
  inquiry_retention_days integer not null default 365,
  privacy_policy_text text not null,
  updated_at timestamptz not null default now()
);

create table if not exists content_items (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  type text not null check (type in ('portfolio', 'service')),
  title text not null,
  slug text not null,
  summary text,
  body text,
  status text not null default 'draft' check (status in ('draft', 'published')),
  thumbnail_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, type, slug)
);

create table if not exists media_assets (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  file_name text not null,
  original_name text not null,
  mime_type text not null,
  file_size bigint not null,
  storage_path text not null,
  created_at timestamptz not null default now()
);

create table if not exists content_media_links (
  id bigint generated by default as identity primary key,
  content_item_id bigint not null references content_items(id) on delete cascade,
  media_asset_id bigint not null references media_assets(id) on delete cascade,
  sort_order integer not null default 0,
  unique (content_item_id, media_asset_id)
);

create table if not exists content_blocks (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  content_item_id bigint not null references content_items(id) on delete cascade,
  block_type text not null check (block_type in ('text', 'image', 'video')),
  content_text text,
  media_asset_id bigint references media_assets(id) on delete set null,
  media_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists inquiries (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  name text not null,
  phone text not null,
  company text not null,
  message text not null,
  status text not null default 'NEW' check (status in ('NEW', 'READ', 'REPLIED', 'CLOSED')),
  consent_given integer not null default 0,
  consent_at timestamptz,
  retention_until timestamptz,
  deleted_at timestamptz,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists inquiry_audit_logs (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  inquiry_id bigint,
  action text not null,
  detail text,
  actor_type text not null check (actor_type in ('public', 'admin', 'system')),
  actor_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_content_blocks_content
  on content_blocks(content_item_id, sort_order);

create index if not exists idx_inquiries_retention
  on inquiries(tenant_id, retention_until);

create index if not exists idx_audit_tenant_created
  on inquiry_audit_logs(tenant_id, created_at);

-- Storage bucket for uploaded images/videos
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'public_read_media'
  ) then
    create policy public_read_media
      on storage.objects
      for select
      to public
      using (bucket_id = 'media');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'service_role_media_all'
  ) then
    create policy service_role_media_all
      on storage.objects
      for all
      to service_role
      using (bucket_id = 'media')
      with check (bucket_id = 'media');
  end if;
end $$;
